<?php
/**
 * DVSwitch Dashboard Auto-Configurator
 * Usage: php setup.php /path/to/P25Reflector.ini
 */

if ($argc < 2) {
    die("Usage: php setup.php /path/to/your/Reflector.ini\n");
}

$iniPath = $argv[1];
if (!file_exists($iniPath)) {
    die("Error: File not found: $iniPath\n");
}

echo "Reading INI: $iniPath...\n";
$iniContent = file_get_contents($iniPath);

// Extract values using robust regex
function getVal($content, $key) {
    if (preg_match('/^\s*' . $key . '\s*=\s*(.*)/m', $content, $matches)) {
        return trim($matches[1]);
    }
    return null;
}

$fileRoot = getVal($iniContent, "FileRoot");
$filePath = getVal($iniContent, "FilePath");

// Derived paths
$iniDir = dirname(realpath($iniPath)) . "/";
$iniFile = basename($iniPath);

// Determine default branding based on FileRoot
$modeParts = explode('_', $fileRoot);
$mode = (count($modeParts) > 0) ? $modeParts[0] : "NETWORK";
$displayName = str_replace('_', ' ', $fileRoot);

$configTemplate = <<<EOD
<?php
/**
 * DVSwitch Universal Reflector Dashboard Configuration
 * Auto-generated by setup.php on %s
 */

date_default_timezone_set('UTC');

// --- 1. Branding & Identity ---
define("DASHBOARD_TITLE", "%s Dashboard");
define("DASHBOARD_SUBTITLE", "Real-time Network Monitoring");
define("LOGO", "DVSwitch.png");

// --- 2. Reflector Connection ---
define("REFLECTOR_LOG_PREFIX", "%s");
define("REFLECTOR_LOG_PATH", "%s");
define("REFLECTOR_INI_PATH", "%s");
define("REFLECTOR_INI_FILE", "%s");
define("REFLECTOR_BIN_PATH", "%s");

// --- 3. UI Features ---
define("SHOWQRZ", "1");
define("SHOW_SYSTEM_STATS", "1");
define("SHOW_NETWORK_PULSE", "1");

// --- 4. Advanced Settings ---
define("API_REFRESH_INTERVAL", "2000");
define("LAST_HEARD_COUNT", "50");
define("TEMPERATUREHIGHLEVEL", "60");
?>
EOD;

$configOutput = sprintf(
    $configTemplate,
    date('Y-m-d H:i:s'),
    strtoupper($mode),
    $fileRoot,
    $filePath ?: "./logs",
    $iniDir,
    $iniFile,
    $iniDir // Assuming bin is in the same dir
);

$targetFile = __DIR__ . "/config/config.php";
if (file_put_contents($targetFile, $configOutput)) {
    echo "Successfully generated: $targetFile\n";
    echo "Reflector Mode: " . strtoupper($mode) . "\n";
    echo "Log Prefix: $fileRoot\n";
} else {
    echo "Error: Failed to write to $targetFile\n";
}
?>
